kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: default

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: install
  image: composer
  commands:
  - composer install
- name: publish
  pull: always
  image: registry.cn-beijing.aliyuncs.com/nfangxu/laravel
