kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: default

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: install
  image: registry.cn-beijing.aliyuncs.com/nfangxu/laranginx:1.1
  commands:
  - composer install
  - cp .env.example .env
  - php artisan key:generate

# - name: publish
#   image: registry.cn-beijing.aliyuncs.com/nfangxu/laranginx:1.1
#   settings:
#     tags: ${DRONE_COMMIT_SHA:0:8}
#     repo: registry-vpc.cn-beijing.aliyuncs.com/nfangxu/laravel

- name: deploy
  image: kubectl:v1.16.2
  commands:
  - kubectl get pods -A