kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: default

trigger:
  branch:
  - master
  event:
  - push

steps:
# - name: install
#   image: registry.cn-beijing.aliyuncs.com/nfangxu/laranginx:1.1
#   commands:
#   - composer install
#   - cp .env.example .env
#   - php artisan key:generate

# - name: publish
#   image: plugins/docker
#   volumes:
#   - name: docker
#     path: /var/run/docker.sock
#   settings:
#     username: 
#       from_secret: aliyun_username
#     password: 
#       from_secret: aliyun_password
#     repo: registry-vpc.cn-beijing.aliyuncs.com/nfangxu/laravel
#     registry: registry-vpc.cn-beijing.aliyuncs.com
#     tags: ${DRONE_BUILD_NUMBER}

- name: deploy
  image: quay.io/ipedrazas/drone-helm
  chart: ./chart
  release: ${DRONE_BRANCH}
  values: image.tag="33"
  namespace: default
  debug: true
  api_server: 
    from_secret: k8s_server
  kubernetes_token: 
    from_secret: k8s_token
  # commands:
  # - helm search fx-web
  # - helm delete laravel --purge || true
  # - helm install fx-web --name laravel --namespace default --host="laravel.nfangxu.cn" --set image.repository="registry-vpc.cn-beijing.aliyuncs.com/nfangxu/laravel" --set image.tag="33" --set ingress.enable=true