# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: drone-laravel
  name: drone-laravel-deploy
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        k8s-app: drone-laravel
    spec:
      image: registry-vpc.cn-beijing.aliyuncs.com/nfangxu/laravel:1.0
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
        name: http
        protocol: TCP
      - containerPort: 443
        name: https
        protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
# service
---
kind: Service
apiVersion: v1
metadata:
  name: drone-laravel-service
  namespace: default
  labels:
    k8s-app: drone-laravel
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: drone-laravel
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None

# ingress
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: drone-laravel-ingress
  namespace: default
  labels:
    k8s-app: drone-laravel
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: drone-laravel.nfangxu.cn
      http:
        paths:
          - path: /
            backend:
              serviceName: drone-laravel
              servicePort: 80
