# deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: drone-laravel-deployment
  namespace: default
  labels:
    k8s-app: drone-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: drone-laravel
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: drone-laravel
    spec:
      containers:
        - name: drone-laravel
          image: 'registry-vpc.cn-beijing.aliyuncs.com/nfangxu/laravel:1.0'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

# service
---
kind: Service
apiVersion: v1
metadata:
  name: drone-laravel-service
  namespace: default
  labels:
    k8s-app: drone-laravel
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: drone-laravel
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None

# ingress
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: drone-laravel-ingress
  namespace: default
  labels:
    k8s-app: drone-laravel
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: drone-laravel.nfangxu.cn
      http:
        paths:
          - path: /
            backend:
              serviceName: drone-laravel-service
              servicePort: 80
