{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fx-web.serviceAccountName" . }}
  labels:
{{ include "fx-web.labels" . | indent 4 }}
{{- end -}}
